# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant_API_Version ="2"

Vagrant.configure(Vagrant_API_Version) do |config|
 #================#
 # Ansible Node #
 #================#

 #Ansible-Node101
 config.vm.define:"ansible-node101" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider:virtualbox do |vb|
    vb.name="Ansible-node101"
    vb.customize ["modifyvm",:id,"--cpus",1]
    vb.customize ["modifyvm",:id,"--memory",512]
  end
  cfg.vm.host_name="ansible-node101"
  cfg.vm.synced_folder ".", "/vagrant", disabled: true
  cfg.vm.network "public_network", ip: "192.168.1.101"
  cfg.vm.network "forwarded_port", guest: 22, host: 19211, auto_correct: false, id: "ssh"
 end

#Ansible-Node102
config.vm.define:"ansible-node102" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider:virtualbox do |vb|
    vb.name="Ansible-Node102"
    vb.customize ["modifyvm",:id,"--cpus",1]
   vb.customize ["modifyvm",:id,"--memory",512]
  end
  cfg.vm.host_name="ansible-node102"
  cfg.vm.synced_folder ".", "/vagrant", disabled: true
  cfg.vm.network "public_network", ip: "192.168.1.102"
  cfg.vm.network "forwarded_port", guest: 22, host: 19212, auto_correct: false, id: "ssh"
 end

 #================#
 # Ansible Server #
 #================#

 config.vm.define:"ansible-server" do |cfg|
  cfg.vm.box = "centos/7"
  cfg.vm.provider:virtualbox do |vb|
    vb.name="Ansible-Server"
  end
  cfg.vm.host_name="ansible-server"
  cfg.vm.synced_folder ".", "/vagrant", disabled: true
  cfg.vm.network "public_network", ip: "192.168.1.10"
  cfg.vm.network "forwarded_port", guest: 22, host: 19210, auto_correct: false, id: "ssh"
  #bootstrap을 전송하고 실행
  cfg.vm.provision "shell", path: "bootstrap.sh"
  #file을 통해 해당 파일을 전송
  cfg.vm.provision "file", source: "Ansible_env_ready.yml", destination: "Ansible_env_ready.yml"
  #cfg.vm.provision "file", source: "Auto_known_host.yml", destination: "Auto_known_host.yml"
  ##  ansible-playbook Ansible_env_ready.yml을 실행
  cfg.vm.provision "shell", inline: "ansible-playbook Ansible_env_ready.yml"
  ## add_ssh_auth.sh 파일을 복사하고 실행한다.
  cfg.vm.provision "shell", path: "add_ssh_auth.sh", privileged:false
  #cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  #cfg.vm.provision "shell", inline: "ansible-playbook Auto_known_host.yml", privileged: false
  #cfg.vm.provision "file", source: "Auto_authorized_keys.yml", destination: "Auto_authorized_keys.yml"
  #cfg.vm.provision "shell", inline: "ansible-playbook Auto_authorized_keys.yml --extra-vars 'ansible_ssh_pass=vagrant'", privileged: false
 end
end